#
# Hisilicon Clock specific Makefile
#

#obj-y	+= clk.o clkgate-separated.o

obj-$(CONFIG_ARCH_HI3xxx)	+= clk.o clkgate-separated.o clk-hi3620.o
obj-$(CONFIG_ARCH_HIP04)	+= clk.o clkgate-separated.o clk-hip04.o
obj-$(CONFIG_ARCH_HIX5HD2)	+= clk.o clkgate-separated.o clk-hix5hd2.o
obj-$(CONFIG_COMMON_CLK_HI6220)	+= clk.o clkgate-separated.o clk-hi6220.o
obj-$(CONFIG_STUB_CLK_HI6220)	+= clk.o clkgate-separated.o clk-hi6220-stub.o
obj-$(CONFIG_ARCH_HI3518)	+= clk-hi3518.o
